// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_ozow/test/domain/ozow_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:flutter_ozow/src/data/data_source/ozow_data_source.dart' as _i3;
import 'package:flutter_ozow/src/data/models/ozow_transaction_model.dart'
    as _i6;
import 'package:flutter_ozow/src/exception.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [OzowApiDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockOzowApiDataSource extends _i1.Mock implements _i3.OzowApiDataSource {
  MockOzowApiDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.OzowException, String?>> generateLink({
    required Map<String, dynamic>? payment,
    required String? apiKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateLink,
          [],
          {
            #payment: payment,
            #apiKey: apiKey,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.OzowException, String?>>.value(
            _FakeEither_0<_i5.OzowException, String?>(
          this,
          Invocation.method(
            #generateLink,
            [],
            {
              #payment: payment,
              #apiKey: apiKey,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.OzowException, String?>>);

  @override
  _i4.Future<_i6.OzowTransactionModel?> getOzowTransaction({
    required String? transactionId,
    required String? siteCode,
    required String? apiKey,
    required bool? isTest,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOzowTransaction,
          [],
          {
            #transactionId: transactionId,
            #siteCode: siteCode,
            #apiKey: apiKey,
            #isTest: isTest,
          },
        ),
        returnValue: _i4.Future<_i6.OzowTransactionModel?>.value(),
      ) as _i4.Future<_i6.OzowTransactionModel?>);
}
